@echo off

cd %~dp0
echo %cd%

mkdir "..\Install"
mkdir "..\Install\NRCan"
mkdir "..\Install\NRCan\External"
mkdir "..\Install\NRCan\Models"
mkdir "..\Install\NRCan\Layers"
::mkdir "..\Install\NRCan\Maps"
mkdir "..\Install\NRCan\Palette"


copy /Y ".\bin\Releasex64\BioSIM11.exe" "..\Install\NRCan\BioSIM11.exe"
copy /Y ".\bin\Releasex64\HourlyEditor.exe" "..\Install\NRCan\HourlyEditor.exe"
copy /Y ".\bin\Releasex64\DailyEditor.exe" "..\Install\NRCan\DailyEditor.exe"
copy /Y ".\bin\Releasex64\NormalsEditor.exe" "..\Install\NRCan\NormalsEditor.exe"
copy /Y ".\bin\Releasex64\WeatherUpdater.exe" "..\Install\NRCan\WeatherUpdater.exe"
copy /Y ".\bin\Releasex64\MatchStation.exe" "..\Install\NRCan\MatchStation.exe"
copy /Y ".\bin\Releasex64\ShowMap.exe" "..\Install\NRCan\ShowMap.exe"
copy /Y ".\bin\Releasex64\ShowMap.exe.manifest" "..\Install\NRCan\ShowMap.exe.manifest"
copy /Y ".\bin\Releasex64\vcomp120.dll" "..\Install\NRCan\vcomp120.dll"
copy /Y ".\bin\Releasex64\gdal19.dll" "..\Install\NRCan\gdal19.dll"


copy /Y ".\bin\Releasex64\Models\ASCE-ET2005.pdf" "..\Install\NRCan\Models\ASCE-ET2005.pdf"
copy /Y ".\bin\Releasex64\Models\ASCE-ETc (Daily).mdl" "..\Install\NRCan\Models\ASCE-ETc (Daily).mdl"
copy /Y ".\bin\Releasex64\Models\ASCE-ETc.dll" "..\Install\NRCan\Models\ASCE-ETc.dll"
copy /Y ".\bin\Releasex64\Models\ASCE-ETcEx (Daily).mdl" "..\Install\Models\NRCan\"
copy /Y ".\bin\Releasex64\Models\ASCE-ETsz (Daily).mdl" "..\Install\NRCan\Models\ASCE-ETsz (Daily).mdl"
copy /Y ".\bin\Releasex64\Models\ASCE-ETsz (Hourly).mdl" "..\Install\NRCan\Models\ASCE-ETsz (Hourly).mdl"
copy /Y ".\bin\Releasex64\Models\ASCE-ETsz.dll" "..\Install\NRCan\Models\ASCE-ETsz.dll"
copy /Y ".\bin\Releasex64\Models\BlueStainIndex.dll" "..\Install\NRCan\Models\BlueStainIndex.dll"
copy /Y ".\bin\Releasex64\Models\BlueStainIndex.mdl" "..\Install\NRCan\Models\BlueStainIndex.mdl"
copy /Y ".\bin\Releasex64\Models\BlueStainVariables.dll" "..\Install\NRCan\Models\BlueStainVariables.dll"
copy /Y ".\bin\Releasex64\Models\BlueStainVariables.mdl" "..\Install\NRCan\Models\BlueStainVariables.mdl"
copy /Y ".\bin\Releasex64\Models\DegreeDay (Annual).mdl" "..\Install\NRCan\Models\DegreeDay (Annual).mdl"
copy /Y ".\bin\Releasex64\Models\DegreeDay (Daily).mdl" "..\Install\NRCan\Models\DegreeDay (Daily).mdl"
copy /Y ".\bin\Releasex64\Models\DegreeDay (Hourly).mdl" "..\Install\NRCan\Models\DegreeDay (Hourly).mdl"
copy /Y ".\bin\Releasex64\Models\DegreeDay (Monthly).mdl" "..\Install\NRCan\Models\DegreeDay (Monthly).mdl"
copy /Y ".\bin\Releasex64\Models\DegreeDay.dll" "..\Install\NRCan\Models\DegreeDay.dll"
copy /Y ".\bin\Releasex64\Models\DegreeDay.pdf" "..\Install\NRCan\Models\DegreeDay.pdf"
copy /Y ".\bin\Releasex64\Models\DewPeriod.dll" "..\Install\NRCan\Models\DewPeriod.dll"
copy /Y ".\bin\Releasex64\Models\GrowingSeason.dll" "..\Install\NRCan\Models\GrowingSeason.dll"
copy /Y ".\bin\Releasex64\Models\HemlockLooper.dll" "..\Install\NRCan\Models\HemlockLooper.dll"
copy /Y ".\bin\Releasex64\Models\HemlockLooper.mdl" "..\Install\NRCan\Models\HemlockLooper.mdl"
copy /Y ".\bin\Releasex64\Models\HemlockLooperRemi.dll" "..\Install\NRCan\Models\HemlockLooperRemi.dll"
copy /Y ".\bin\Releasex64\Models\HemlockLooperRemi.mdl" "..\Install\NRCan\Models\HemlockLooperRemi.mdl"
copy /Y ".\bin\Releasex64\Models\Jack Pine Budworm.dll" "..\Install\NRCan\Models\Jack Pine Budworm.dll"
copy /Y ".\bin\Releasex64\Models\Jack Pine Budworm.mdl" "..\Install\NRCan\Models\Jack Pine Budworm.mdl"
copy /Y ".\bin\Releasex64\Models\Potential Evapotranspiration (Annual).mdl" "..\Install\NRCan\Models\Potential Evapotranspiration (Annual).mdl"
copy /Y ".\bin\Releasex64\Models\Potential Evapotranspiration (Daily).mdl" "..\Install\NRCan\Models\Potential Evapotranspiration (Daily).mdl"
copy /Y ".\bin\Releasex64\Models\Potential Evapotranspiration (Hourly).mdl" "..\Install\NRCan\Models\Potential Evapotranspiration (Hourly).mdl"
copy /Y ".\bin\Releasex64\Models\Potential Evapotranspiration (Monthly).mdl" "..\Install\NRCan\Models\Potential Evapotranspiration (Monthly).mdl"
copy /Y ".\bin\Releasex64\Models\Potential Evapotranspiration.dll" "..\Install\NRCan\Models\Potential Evapotranspiration.dll"
copy /Y ".\bin\Releasex64\Models\ReverseDegreeDay (Annual).mdl" "..\Install\NRCan\Models\ReverseDegreeDay (Annual).mdl"
copy /Y ".\bin\Releasex64\Models\ReverseDegreeDay (Overall years).mdl" "..\Install\NRCan\Models\ReverseDegreeDay (Overall years).mdl"
copy /Y ".\bin\Releasex64\Models\ReverseDegreeDay.dll" "..\Install\NRCan\Models\ReverseDegreeDay.dll"
copy /Y ".\bin\Releasex64\Models\ReverseDegreeDay.pdf" "..\Install\NRCan\Models\ReverseDegreeDay.pdf"
copy /Y ".\bin\Releasex64\Models\Spruce Budworm Biology.dll" "..\Install\NRCan\Models\Spruce Budworm Biology.dll"
copy /Y ".\bin\Releasex64\Models\Spruce Budworm Biology.mdl" "..\Install\NRCan\Models\Spruce Budworm Biology.mdl"
copy /Y ".\bin\Releasex64\Models\Spruce Budworm Grow Rate.mdl" "..\Install\NRCan\Models\Spruce Budworm Grow Rate.mdl"
copy /Y ".\bin\Releasex64\Models\Tranosema Biology (daily).mdl" "..\Install\NRCan\Models\Tranosema Biology (daily).mdl"
copy /Y ".\bin\Releasex64\Models\Tranosema Biology.dll" "..\Install\NRCan\Models\Tranosema Biology.dll"
copy /Y ".\bin\Releasex64\Models\Tranosema Grow Rate (annual).mdl" "..\Install\NRCan\Models\Tranosema Grow Rate (annual).mdl"
copy /Y ".\bin\Releasex64\Models\Tranosema Grow Rate (generation).mdl" "..\Install\NRCan\Models\Tranosema Grow Rate (generation).mdl"
copy /Y ".\bin\Releasex64\Models\Western Spruce Budworm (annual).mdl" "..\Install\NRCan\Models\Western Spruce Budworm (annual).mdl"
copy /Y ".\bin\Releasex64\Models\Western Spruce Budworm.dll" "..\Install\NRCan\Models\Western Spruce Budworm.dll"
copy /Y ".\bin\Releasex64\Models\Western Spruce Budworm.mdl" "..\Install\NRCan\Models\Western Spruce Budworm.mdl"
copy /Y ".\bin\Releasex64\Models\WetnessDuration (Hourly).mdl" "..\Install\NRCan\Models\WetnessDuration (Hourly).mdl"
copy /Y ".\bin\Releasex64\Models\WetnessDuration.dll" "..\Install\NRCan\Models\WetnessDuration.dll"
copy /Y ".\bin\Releasex64\Models\WhitePineWeevil.mdl" "..\Install\NRCan\Models\WhitePineWeevil.mdl"
copy /Y ".\bin\Releasex64\Models\WhitePineWeevil.dll" "..\Install\NRCan\Models\WhitePineWeevil.dll"
copy /Y ".\bin\Releasex64\Models\Yellowheaded Spruce Sawfly.dll" "..\Install\NRCan\Models\Yellowheaded Spruce Sawfly.dll"
copy /Y ".\bin\Releasex64\Models\Yellowheaded Spruce Sawfly.mdl" "..\Install\NRCan\Models\Yellowheaded Spruce Sawfly.mdl"
copy /Y ".\bin\Releasex64\Models\Yellowheaded Spruce Sawfly.pdf" "..\Install\NRCan\Models\Yellowheaded Spruce Sawfly.pdf"


xcopy /Y /S ".\bin\Releasex64\External\*.*" "..\Install\NRCan\External\*.*"
xcopy /Y /S ".\bin\Releasex64\Layers\*.*" "..\Install\NRCan\Layers\*.*"
xcopy /Y /S ".\bin\Releasex64\Palette\*.*" "..\Install\NRCan\Palette\*.*"
xcopy /Y /S ".\bin\Releasex64\zoneinfo\*.*" "..\Install\NRCan\zoneinfo\*.*"

::copy /Y ".\bin\Releasex64\External\FTPTransfer.exe" "..\Install\NRCan\External\FTPTransfer.exe"

del "..\Install\BioSIM11_x_x.7z"
.\bin\Releasex64\External\7z.exe a -r "..\Install\BioSIM11_x_x.7z" "..\Install\NRCan"
del "..\Install\BioSIM11_x_x.zip"
.\bin\Releasex64\External\7z.exe a -r "..\Install\BioSIM11_x_x.zip" "..\Install\NRCan"

REM ::xcopy /Y "..\Install\NRCan.7z" "ftp://ftp.cfl.scf.rncan.gc.ca/regniere/software/BioSIM/BioSIM11_x_x.7z"

