//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WeatherBasedSimulationUI.rc
//
#define IDB_TEST_PNG                    196
#define IDB_UI_MODEL_ICONS              197
#define IDD_SIM_LOC_EXTRACT             200
#define IDR_MENU1                       202
#define IDR_MENU_EDIT                   202
#define IDR_CMN_BROWSETITLE             940
#define IDR_CMN_PROJECT_EXIST           941
#define IDR_SHOWMAP_TOOLBAR             942
#define IDR_EDIT_TOOLBAR                943
#define IDR_LOC_TOOLBAR                 944
#define IDR_PROJECT_TOOLBAR1            945
#define IDR_PROJECT_TOOLBAR2            946
#define IDC_CURSOR_GROUP                1000
#define IDC_CMN_NEW_YEAR                1000
#define IDC_USE_EXTENT                  1000
#define IDC_LP_CHANGE_PROJECTION        1000
#define IDC_PT_LAT1_IN                  1000
#define IDC_SELECT_STATISTIC            1000
#define IDC_INITIAL_TEMPERATURE         1000
#define IDC_CMN_NEW_NAME                1001
#define IDC_CMN_OPTION_LIST_DELIMITER   1001
#define IDC_LP_CHANGEFONT               1001
#define IDC_PT_LAT2_IN                  1001
#define IDC_MEAN_OVER_REPLICATION       1001
#define IDC_T_REDUCTION                 1001
#define IDC_TRANSFO_LOGX                1001
#define IDC_LP_CHANGEPALETTE            1002
#define IDC_PT_LON1_IN                  1002
#define IDC_MEAN_OVER_PARAMETERSET      1002
#define IDC_GRAPH_XAXIS                 1002
#define IDC_GRAPH_TYPE                  1002
#define IDC_SIM_DESCRIPTION             1002
#define IDC_NB_CYCLES                   1002
#define IDC_TRANSFO_LOGX1               1002
#define IDC_LP_FIELD                    1003
#define IDC_PT_LON2_IN                  1003
#define IDC_MEAN_OVER_LOCATION          1003
#define IDC_SIM_MODEL                   1003
#define IDC_ERROR_TOLERENCE             1003
#define IDC_CMN_STEPNO                  1004
#define IDC_LP_FILENAME                 1004
#define IDC_PT_NBCOLS_IN                1004
#define IDC_SIM_HELP                    1004
#define IDC_NB_ITERATION                1004
#define IDC_TRANSFO_PPRIME              1004
#define IDC_CMN_STEP_DESCRIPTION        1005
#define IDC_LP_FILL_COLOR               1005
#define IDC_MAP_VARIOGRAM_MODEL         1005
#define IDC_PT_NBROWS_IN                1005
#define IDC_SIM_REPLICATION             1005
#define IDC_DELTA_VAR                   1005
#define IDC_TRANSFO_PPRIME2             1005
#define IDC_TRANSFO_PERCENT             1005
#define IDC_CMN_STEP_POURCENTAGE        1006
#define IDC_LP_FILL_STYLE               1006
#define IDC_MAP_DETRENDING              1006
#define IDC_SAVE_MASK                   1006
#define IDC_PT_CELLSIZE_IN              1006
#define IDC_GRAPH_VARIABLE              1006
#define IDC_SIM_MODELINPUT              1006
#define IDC_TRANFO_NOTRANSFO            1006
#define IDC_CMN_MAILTO_REMI             1007
#define IDC_CMN_STEP_BITMAP             1007
#define IDC_LP_FONTNAME                 1007
#define IDC_MAP_LAGDIST                 1007
#define IDC_PT_LAT1_OUT                 1007
#define IDC_GRAPH_SHOW_LEGEND           1007
#define IDC_SIM_MODELINPUT_EDITOR       1007
#define IDC_TRANSFO_LOG                 1007
#define IDC_CMN_STEP_PROGRESS           1008
#define IDC_LP_FORM_SIZE                1008
#define IDC_MAP_IWD_MODEL               1008
#define IDC_MASK_SAVE_NAME              1008
#define IDC_PT_LAT2_OUT                 1008
#define IDC_GRAPH_TITLE                 1008
#define IDC_SIM_TGINPUT                 1008
#define IDC_TRANSFO_LOGIT               1008
#define IDC_CMN_STEP_MESSAGE            1009
#define IDC_LP_FORM_SIZE2               1009
#define IDC_MAP_EXTERNAL_DRIFT          1009
#define IDC_PT_LON1_OUT                 1009
#define IDC_GRAPH_NAME                  1009
#define IDC_SIM_TGINPUT_EDITOR          1009
#define IDC_LP_FORM_STYLE               1010
#define IDC_PT_LON2_OUT                 1010
#define IDC_GRAPH_X_TITLE               1010
#define IDC_SIM_LOC                     1010
#define IDC_CMN_ADD_DIRECTORY_LIST      1011
#define IDC_CMN_SELECT_UNUSED           1011
#define IDC_LP_INCLUDE_LOWERMIN         1011
#define IDC_MAP_POWER                   1011
#define IDC_MASK_UNUSED                 1011
#define IDC_PT_NBCOLS_OUT               1011
#define IDC_GRAPH_Y_TITLE               1011
#define IDC_SIM_LOC_EDITOR              1011
#define IDC_CMN_SELECT_ADD              1012
#define IDC_LP_INCLUDE_UPPERMAX         1012
#define IDC_MASK_ADD                    1012
#define IDC_PT_NBROWS_OUT               1012
#define IDC_SIM_SPIN                    1012
#define IDC_SIM_PARAMETERS_VARIATIONS_EDITOR 1012
#define IDC_CMN_NEWPRJ_ICON             1013
#define IDC_CMN_SELECT_REMOVE           1013
#define IDC_LP_INFO_FIELD               1013
#define IDC_MASK_REMOVE                 1013
#define IDC_PT_CELLSIZE_OUT             1013
#define IDC_SIM_ADVANCE                 1013
#define IDC_CMN_PAUSE                   1014
#define IDC_CMN_SELECT_USED             1014
#define IDC_LP_LEGEND_FORMAT            1014
#define IDC_MASK_USED                   1014
#define IDC_PT_EXTRACT_METHOD           1014
#define IDC_SIM_NBRUN                   1014
#define IDC_SIM_RESULT                  1014
#define IDC_TRANSFO_N                   1014
#define IDC_CMN_EXTRA                   1015
#define IDC_LP_MANUALSCALE              1015
#define IDC_SIM_TIME                    1015
#define IDC_SIM_LOCID_FIELD             1015
#define IDC_TRANSFO_SPIN                1015
#define IDC_CMN_OPTION_CHARTS_MAX_DATA  1016
#define IDC_LP_MAX                      1016
#define IDC_SIM_ABOUT                   1016
#define IDC_CMN_OPTION_NB_PIXEL_PER_X   1017
#define IDC_LP_MIN                      1017
#define IDC_MASK_FILEPATH               1017
#define IDC_SIM_PARAMETERS_SET          1017
#define IDC_OPTIMISATION_TYPE           1017
#define IDC_SIM_LINK_CLIMZONE           1017
#define IDC_LP_NBCLASS                  1018
#define IDC_MAX_ELVA                    1018
#define IDC_SIM_HELP2                   1018
#define IDC_LP_OUTLINE_COLOR            1019
#define IDC_SEED1                       1019
#define IDC_LP_OUTLINE_SIZE             1020
#define IDC_USE_MASK                    1020
#define IDC_STATISTIC                   1020
#define IDC_SEED2                       1020
#define IDC_LP_OUTLINE_STYLE            1021
#define IDC_EVENT                       1021
#define IDC_NB_ESP                      1021
#define IDC_LP_PALETTE_NAME             1022
#define IDC_LP_PATH                     1023
#define IDC_LP_PERMANANT                1024
#define IDC_LP_PROJECTIONTYPE           1025
#define IDC_STATISTIC_TYPE              1025
#define IDC_SIMUL_PARAM_LIST            1025
#define IDC_TG_STATIC12                 1026
#define IDC_LP_SHOW_INFOBULE            1026
#define IDC_EVENT_TYPE                  1026
#define IDC_OUTPUT_HEIGHT               1027
#define IDC_LP_SHOW_LEGEND              1027
#define IDC_TT_TYPE                     1027
#define IDC_LP_SINGLE_VALUE             1028
#define IDC_CMN_VERSION                 1029
#define IDC_OUTPUT_WIDTH                1029
#define IDC_LP_UNIQUE_VALUE             1029
#define IDC_CRF_FILEPATH_IN_BROWSE      1030
#define IDC_LP_RANGE_VALUE              1030
#define IDC_TT_MODE                     1030
#define IDC_CRF_FILEPATH_OUT_BROWSE     1031
#define IDC_LP_TRANSPARENCE_TYPE        1031
#define IDC_K                           1031
#define IDC_LP_TRANSPARENT_SLIDER       1032
#define IDC_CRF_TYPE_IN                 1033
#define IDC_NO_FIELD                    1033
#define IDC_SHIFT1                      1033
#define IDC_CONTINUOUS                  1034
#define IDC_MAPIN_LON1                  1035
#define IDC_MASK_FIELD                  1035
#define IDC_YEAR_BY_YEAR                1035
#define IDC_MAPIN_LON2                  1036
#define IDC_SHOW_ALL_MASK_FIELD         1036
#define IDC_BEGIN                       1036
#define IDC_MAPIN_LAT1                  1037
#define IDC_END                         1037
#define IDC_SHIFT2                      1038
#define IDC_CURRENT_OUTPUT_CELLSIZE     1039
#define IDC_USE_CURRENT_DATE1           1039
#define IDC_MAPIN_LAT2                  1040
#define IDC_SELECT_PERIOD               1040
#define IDC_USE_CURRENT_DATE2           1041
#define IDC_SELECT_LOCATION             1041
#define IDC_WG_SOURCE_TYPE              1042
#define IDC_CMN_NODROP                  1042
#define IDC_SELECT_VARIABLE             1042
#define IDC_WG_GENERATION_TYPE          1043
#define IDC_CMN_DROPCOPY                1043
#define IDC_NAME                        1043
#define IDC_CMN_DROPMOVE                1044
#define IDC_DESCRIPTION                 1044
#define IDC_INTERNAL_NAME               1045
#define IDC_LOCATION                    1046
#define IDC_OUTPUT_FILE_PATH            1046
#define IDC_USER_NAME                   1047
#define IDC_MAP_TRANFORM                1047
#define IDC_PASSWORD                    1048
#define IDC_CT_TYPE                     1049
#define IDC_CT_MODE                     1050
#define IDC_SHOW_GRAPH                  1054
#define IDC_RT_ADD_LINK                 1057
#define IDC_RT_REMOVE_LINK              1059
#define IDC_VARIABLES                   1061
#define IDC_VARIABLE                    1061
#define IDC_MODELS_NAME                 1066
#define IDC_METRE                       1066
#define IDC_PT_FILEPATH_OUT_BROWSE      1066
#define IDC_PT_PROJECTIONTYPE_OUT       1067
#define IDC_MODE_IMAGE                  1067
#define IDC_SIM_SA                      1067
#define IDC_PT_CHANGE_PROJECTION_OUT    1068
#define IDC_SIM_USE_HXGRID              1068
#define IDC_MODELS_VERSION              1069
#define IDC_MERGE_FILEPATH_IN           1070
#define IDC_RT_UNLINKED                 1071
#define IDC_MODELS_DLLVERSION           1071
#define IDC_MERGE_FILEPATH_OUT          1071
#define IDC_RT_LINKED                   1072
#define IDC_MERGE_FILEPATH_OUT_BROWSE   1072
#define IDC_DROP_YEAR                   1072
#define IDC_MERGE_CELLESIZE_TYPE        1073
#define IDC_IMPORT_TEMPORAL_DATA        1073
#define IDC_MERGE_ADD                   1074
#define IDC_MAP_VMIN                    1074
#define IDC_MAP_VMAX                    1075
#define IDC_IMPORT_COLUMN_LINK          1076
#define IDC_MAP_NBLAGS                  1077
#define IDC_IMPORT_INTERNAL_NAME        1077
#define IDC_MODELS_CREDITTEXT           1078
#define IDC_MAP_DESCRIPTION             1079
#define IDC_CMN_BITMAP                  1081
#define IDC_CMN_OPTION_MAP_PATH         1087
#define IDC_CMN_OPTION_ADD1             1088
#define IDC_CMN_OPTION_RUN_MISSING_YEAR 1089
#define IDC_CMN_OPTION_REMOVE_TMP_FILE  1090
#define IDC_CMN_OPTION_MAX_DISTANCE1    1091
#define IDC_CMN_OPTION_HXGRID           1092
#define IDC_CMN_OPTION_WEATHER_PATH     1092
#define IDC_CMN_OPTION_PROJECT_WEATHER_PATH 1093
#define IDC_CMN_OPTION_PROJECT_MAP_PATH 1094
#define IDC_MAP_ADD_TERM                1095
#define IDC_TEST                        1100
#define IDC_NORMAL_DATA                 1101
#define IDC_VARIABLE_LIST               1101
#define IDC_FUNCTION_LIST               1102
#define IDC_INPUT_VARIABLE              1102
#define IDC_FUNCTION_HELP               1103
#define IDC_OUTPUT_VARIABLE             1103
#define IDC_MODELS_NBYEAR_MIN           1107
#define IDC_MODELS_NBYEAR_MAX           1108
#define IDC_MODELS_MISSING_VALUE        1109
#define IDC_MODELS_TRANSFER_FILE_VERSION 1110
#define IDC_EXECUTABLE_TREE             1110
#define IDC_RT_IMPORT                   1111
#define IDC_CMN_NEWPRJ_BROWSE           1111
#define IDC_CMN_OPTION_DECIMAL_DELIMITER 1111
#define IDC_GENLOC_SELECTDEM            1111
#define IDC_MODELS_IO_FILE_VERSION      1112
#define IDC_KIND                        1112
#define IDC_CMN_OPTION_PLT              1114
#define IDC_SIM_FEEDBACK                1116
#define IDC_MAP_USE_HXGRID              1117
#define IDC_MODELS_OUTPUT_VAR           1118
#define IDC_MAP_XVAL_ONLY               1118
#define IDC_GRAPH_COLOR                 1119
#define IDC_MODELS_OUTPUT_TYPE          1120
#define IDC_MODELS_OUTPUT_MODE          1121
#define IDC_GRAPH_POINT_SYMBOL          1121
#define IDC_GRAPH_LINE_STYLE            1122
#define IDC_GRAPH_POINT_SIZE            1123
#define IDC_MODEL_LIST                  1124
#define IDC_GRAPH_LINE_WIDTH            1124
#define IDC_MODELS_DLLNAME              1125
#define IDC_MAP_NBPOINT                 1125
#define IDC_GRAPH_SMOOTH                1125
#define IDC_CMN_OPTION_TIME_FORMAT      1127
#define IDC_MAP_NO_DATA                 1127
#define IDC_WG_XVALIDATION              1128
#define IDC_MAP_MAX_DISTANCE            1128
#define IDC_SIM_XVALIDATION             1128
#define IDC_WG_USE_RADARS_PRCP          1129
#define IDC_GENLOC_BOUNDINGBOX          1129
#define IDC_DIMENSION_MERGED            1129
#define IDC_SIM_WEATHER_LOC             1129
#define IDC_MODELS_EXTENSION            1130
#define IDC_GENLOC_EXPOSURE             1130
#define IDC_WG_XVALIDATION2             1130
#define IDC_MODEL_FILEPATH              1131
#define IDC_IMPORT_FILENAME             1131
#define IDC_SIM_NAME                    1131
#define IDC_SIMUL_REMOVEVARIABLE        1131
#define IDC_SIM_INTERNAL_NAME           1132
#define IDC_SIMUL_VARIABLE_LIST         1132
#define IDC_IMPORT_DEFAULT_DIR          1133
#define IDC_SIMUL_VARMIN                1133
#define IDC_SIMUL_VARMAX                1134
#define IDC_MODELS_OUTPUT_JULIAN_DAY    1135
#define IDC_EF_NONE                     1135
#define IDC_SIMUL_VARSTEP               1135
#define IDC_EF_USE_ID                   1136
#define IDC_CMN_OPTION_RUN_EVEN_FAR     1137
#define IDC_EF_SPECIFIC                 1137
#define IDC_SIM_SEED_TYPE               1137
#define IDC_EF_FIELD                    1138
#define IDC_MAP_NAME                    1138
#define IDC_GENLOC_DAILY_NAME           1139
#define IDC_LOC_STATION_LIST            1140
#define IDC_GENLOC_HOURLY_NAME          1140
#define IDC_PE_PALETTE_RANGE            1143
#define IDC_PE_PALETTE_FIXE             1144
#define IDC_SIM_BEHAVIOUR               1144
#define IDC_MODELIN_FILEPATH            1145
#define IDC_PE_LIST                     1145
#define IDC_GRAPH_FIRST_LINE            1145
#define IDC_SIMUL_ADDVARIABLE           1145
#define IDC_MODELIN_LIST                1146
#define IDC_PE_NEW                      1146
#define IDC_GRAPH_LAST_LINE             1146
#define IDC_PE_DELETE                   1147
#define IDC_LATITUDE                    1148
#define IDC_PE_IMPORT                   1148
#define IDC_LONGITUDE                   1149
#define IDC_PE_RANGE_COLOR              1149
#define IDC_PREVIOUS_STATISTIC_TYPE     1149
#define IDC_MODELS_BEHAVIOUR            1150
#define IDC_PE_FIXED_COLOR              1150
#define IDC_MODELS_INPUT_PARAMETERS     1151
#define IDC_SELECT_TIME_TRANSFORMATION  1151
#define IDC_MODELS_WITYPE               1152
#define IDC_FINAL_COMPUTATION_RADIO     1152
#define IDC_DAILYDB_LIST                1153
#define IDC_PE_UP                       1153
#define IDC_TIME_TRANSFORMATION_RADIO   1153
#define IDC_DAILYDB_FILEPATH            1154
#define IDC_PE_DOWN                     1154
#define IDC_NORMALDB_LIST               1155
#define IDC_PE_COLOR_NEW                1155
#define IDC_SIM_PARAM_VARIATIONS_EDITOR 1155
#define IDC_NORMALDB_FILEPATH           1156
#define IDC_PE_COLOR_DELETE             1156
#define IDC_SIM_REPLICATIONS            1156
#define IDC_SIM_PARAM_VARIATIONS_EDITOR2 1156
#define IDC_MAPINPUT_LIST               1157
#define IDC_CMN_OPTION_HOURLY           1157
#define IDC_MAPINPUT_FILEPATH           1158
#define IDC_MODELS_THREAD_SAFE          1159
#define IDC_SIM_WGINPUT_EDITOR          1160
#define IDC_SIM_WGINPUT                 1161
#define IDC_MODELS_TEST                 1162
#define IDC_MODEL_DESCRIPTION           1162
#define IDC_CHARTS                      1163
#define IDC_SIM_PROPERTIES              1163
#define IDC_SERIES                      1164
#define IDC_SERIES_PROPERTY             1165
#define IDC_MAP_INTERNAL_NAME           1165
#define IDC_SIM_ADD_NAME                1166
#define IDC_WG_VARIABLES                1167
#define IDC_PV_PROPERTIES               1168
#define IDC_WG_ALLOWED_DERIVED_VARIABLES 1168
#define IDC_PV_GENERATION_TYPE          1174
#define IDC_PV_NB_VARIATIONS            1175
#define IDC_PV_PARAMETERS               1177
#define IDC_PT_FILEPATH_IN              1177
#define IDC_WG_ALBEDO                   1178
#define IDC_PT_FILEPATH_OUT             1178
#define IDC_WG_NORMALS_NB_STATIONS      1179
#define IDC_PT_FILEPATH_IN_BROWSE       1179
#define IDC_WG_DAILY_NB_STATIONS        1180
#define IDC_PT_PROJECTIONTYPE_IN        1180
#define IDC_WG_NORMALS_DBNAME           1181
#define IDC_PT_CHANGE_PROJECTION_IN     1181
#define IDC_WG_NORMALS_LINK             1182
#define IDC_MAP_DEM_FILENAME            1182
#define IDC_WG_DAILY_LINK               1183
#define IDC_MAP_TEM_FILENAME            1183
#define IDC_WG_SEED                     1184
#define IDC_MAP_OPTIONS                 1184
#define IDC_WG_FIRST_YEAR               1185
#define IDC_WG_LAST_YEAR                1186
#define IDC_MAP_EDITOR                  1186
#define IDC_WG_USE_FORECASTS            1187
#define IDC_WG_HOURLY_DBNAME            1188
#define IDC_CRF_FILEPATH_IN             1188
#define IDC_MAP_ADVANCED                1188
#define IDC_WG_DAILY_DBNAME             1189
#define IDC_WG_HOURLY_LINK              1190
#define IDC_CRF_FILEPATH_OUT            1190
#define IDC_WG_HOURLY_NB_STATIONS       1191
#define IDC_SIMUL_NBVARIATION           1191
#define IDC_WG_GRIBS_DBNAME             1192
#define IDC_WG_NORMALS_DBNAME2          1193
#define IDC_RS_FILEPATH_IN              1193
#define IDC_WG_GRIBS_LINK               1193
#define IDC_WG_NB_YEARS                 1194
#define IDC_RS_FILEPATH_IN_BROWSE       1194
#define IDC_MODELS_VARIABLES            1195
#define IDC_RS_FIELD_NAME               1195
#define IDC_WG_GRIBS_NB_NEAREST         1195
#define IDC_MODELS_SSI                  1196
#define IDC_RS_SHOW_ALL_FIELD           1196
#define IDC_SIMUL_RANDOM                1196
#define IDC_MFCBUTTON1                  1197
#define IDC_RS_UNUSED                   1197
#define IDC_SIMUL_REGULAR               1197
#define IDC_HOURLYDB_LIST               1198
#define IDC_DATETIMEPICKER1             1198
#define IDC_RS_USED                     1198
#define IDC_HOURLYDB_FILEPATH           1199
#define IDC_RS_ADD                      1199
#define IDC_RS_REMOVE                   1200
#define IDC_MFCMENUBUTTON1              1201
#define IDC_FROM_MODEL                  1201
#define IDC_RS_FILEPATH_OUT             1201
#define IDC_DB_LIST                     1202
#define IDC_RS_FILEPATH_OUT_BROWSE      1202
#define IDC_DB_FILEPATH                 1203
#define IDC_CRF_OUTPUT_NODATA           1204
#define IDC_CRF_LONG_NAME_IN            1206
#define IDC_MAP_INPUT_FILEPATH          1206
#define IDC_MAP_OUTPUT_FILEPATH         1207
#define IDC_MAP_INPUT_PROJECTION_TYPE   1208
#define IDC_MFCSHELLTREE1               1208
#define IDC_MAP_INPUT_PROJECTION        1209
#define IDC_TRANSFO_X_PRIME             1210
#define IDC_MAP_INPUT_FILEPATH1         1212
#define IDC_MAP_CHANGE_PROJECTION       1212
#define IDC_SSI_METHOD                  1212
#define IDC_MAP_OUTPUT_PROJECTION_TYPE  1213
#define IDC_MFCEDITBROWSE1              1213
#define IDC_GRID_FILE_PATH              1213
#define IDC_MAP_OUTPUT_PROJECTION       1214
#define IDC_MAP_SHAPE_FIT_ORIGINAL      1215
#define IDC_MAP_NEAREST                 1216
#define IDC_TREE1                       1216
#define IDC_MAP_TREE                    1216
#define IDC_MAP_BILINEAR                1217
#define IDC_WG_SKIP_VERIFY              1217
#define IDC_MAP_CUBIC                   1218
#define IDC_WG_USE_GRIBS                1218
#define IDC_MAP_INPUT_HEIGHT            1219
#define IDC_WG_AT_SURFACE               1219
#define IDC_MAP_INPUT_WIDTH             1220
#define IDC_MAP_LAT1                    1221
#define IDC_GENLOC_STATION_TYPE         1221
#define IDC_MFCPROPERTYGRID1            1221
#define IDC_PROPERTIES                  1221
#define IDC_MAP_LAT2                    1222
#define IDC_GENLOC_NORMAL_NAME          1222
#define IDC_MAP_LON2                    1223
#define IDC_GENLOC_FILTER               1223
#define IDC_MAP_LON1                    1224
#define IDC_GENLOC_YEAR                 1224
#define IDC_MAP_SET_EXTENT              1225
#define IDC_MAP_SET_EXTENT_FROM_MAPINT  1226
#define IDC_GENLOC_FACTOR               1226
#define IDC_MAP_CHANGE_RESOLUTION       1227
#define IDC_MAP_OUTPUT_CELLSIZE         1228
#define IDC_MAP_OUTPUT_CELLSIZE_M       1229
#define IDC_MAP_INPUT_CELLSIZE          1230
#define IDC_MAP_INPUT_CELLSIZE_M        1231
#define IDC_MAP_EXTRACT_ELEV            1232
#define IDC_MAP_EXTRACT_EXPOSITION      1233
#define IDC_MAP_INPUT_FILEPATH2         1234
#define IDC_MAP_EXTRACT_EXPOSITION2     1234
#define IDC_MAP_EXTRACT_OTHER           1234
#define IDC_MAP_EXTRACT_MISSING         1235
#define IDC_CRF_TYPE_OUT                1237
#define IDC_CRF_LONG_NAME_OUT           1238
#define IDC_CRF_OVERWRITE_NODATA        1239
#define IDC_MAP_TPS_TYPE                1245
#define IDC_MAP_REGIONAL_LIMIT_TO_BOUND 1246
#define IDC_MAP_GLOBAL_LIMIT_TO_BOUND   1247
#define IDC_MAP_REGIONAL_LIMIT_SD       1248
#define IDC_MAP_GLOBAL_LIMIT_SD         1249
#define IDC_MAP_REGIONAL_LIMIT          1250
#define IDC_MAP_GLOBAL_LIMIT            1251
#define IDC_MAP_GLOBAL_MINMAX_LIMIT_TO_BOUND 1252
#define IDC_MAP_GLOBAL_LIMIT_MIN        1253
#define IDC_MAP_GLOBAL_LIMIT_MAX        1254
#define IDC_MAP_OUTPUT_VARIOGRAM_INFO   1255
#define IDC_MAP_GLOBAL_MINMAX_LIMIT     1256
#define IDC_CMN_NEWPRJ_NAME             1350
#define IDC_CMN_NEWPRJ_PATH             1351
#define IDC_CMN_OPTION_MODELPATH        1354
#define IDC_CMN_OPTION_APPPATH          1355
#define IDC_CMN_OPTION_MAP_EXT          1357
#define IDC_CMN_OPTION_SHOWMAP          1358
#define IDC_CMN_OPTION_PLT_WIDGET       1359
#define IDC_CMN_OPTION_SPREADSHEET      1360
#define IDC_CMN_OPTION_NOTEPAD          1361
#define IDC_CMN_OPTION_NORMALS          1362
#define IDC_CMN_OPTION_DAILY            1363
#define IDC_CMN_OPTION_CLIMZONES        1364
#define IDC_CMN_OPTION_MERGEFILES       1365
#define IDC_CMN_OPTION_SCRIPT           1366
#define IDC_CMN_OPTION_WEATHER_UPDATER  1367
#define IDC_MAP_DEFAULT_DIR             1420
#define IDC_MAP_NB_CREATED              1421
#define IDC_SIMUL_MATCH_STATION         1484
#define IDC_CALENDAR                    1496
#define IDC_GENLOC_NO_EXPOSITION        1534
#define IDC_GENLOC_EXPOSITION_FROM_DEM  1535
#define IDC_GENLOC_EXPOSITION           1536
#define IDC_MODELS_DESCRIPTION          1577
#define IDC_MODELS_COPYRIGHT            1578
#define IDC_MODELS_DOCUMENTATION_FILE   1582
#define IDC_MAP_METHOD                  1597
#define IDC_GENLOC_FROM                 1606
#define IDC_GENLOC_NBPOINT_LAT          1618
#define IDC_GENLOC_NBPOINT              1619
#define IDC_GENLOC_NBPOINT_LON          1620
#define IDC_GENLOC_METHOD               1621
#define IDC_GENLOC_DEM_NAME             1622
#define IDC_GENLOC_METHOD_W             1623
#define IDC_GENLOC_NBSTATION            1624
#define IDC_CMN_OPTION_ADD2             1629
#define IDC_CMN_OPTION_MAX_DISTANCE2    1630
#define IDC_CMN_OPTION_MAX_THREADS      1631
#define IDC_MAP_TRANSFO_INFO            1633
#define IDC_GENLOC_UNIFORM              1635
#define IDC_GENLOC_NORMAL               1636
#define IDC_GENLOC_EXTREM               1645
#define IDC_CMN_OPTION_ERROR_LEVEL      1649
#define IDC_CMN_STATIC1                 1741
#define IDC_CMN_STATIC2                 1742
#define IDC_CMN_STATIC3                 1743
#define IDC_CMN_STATIC4                 1744
#define IDC_CMN_STATIC5                 1745
#define IDC_CMN_STATIC6                 1746
#define IDC_CMN_STATIC7                 1747
#define IDC_CMN_STATIC8                 1748
#define IDC_CMN_STATIC9                 1749
#define IDC_CMN_STATIC10                1750
#define IDC_CMN_STATIC11                1751
#define IDC_CMN_STATIC12                1752
#define IDC_CMN_STATIC13                1753
#define IDC_CMN_STATIC14                1754
#define IDC_CMN_STATIC15                1755
#define IDC_CMN_STATIC16                1756
#define IDC_CMN_STATIC17                1757
#define IDC_CMN_STATIC18                1758
#define IDC_CMN_STATIC19                1759
#define IDC_CMN_STATIC20                1760
#define IDC_CMN_STATIC21                1761
#define IDC_STATION_NAME                2000
#define IDC_STATION_ID                  2001
#define IDC_STATION_ELEVATION           2006
#define IDC_STATION_DISABLE             2007
#define IDC_CURSOR_ADD                  2405
#define IDC_CURSOR_DELETE               2406
#define IDC_CURSOR_MOVE                 2407
#define IDC_CURSOR_SPLIT                2408
#define IDC_CURSOR_CUT                  2409
#define IDI_HEART                       10201
#define IDI_DBEDIT_MODEL                10202
#define IDI_LINK                        10203
#define IDI_LINKED_DATA_EDITOR          10204
#define IDI_NORMALS_EDITOR              10205
#define IDI_DAILY_EDITOR                10206
#define IDI_HOURLY_EDITOR               10207
#define IDI_DOWN                        10221
#define IDI_UP                          10222
#define IDI_NEW                         10223
#define IDI_DELETE                      10224
#define IDI_ADD                         10229
#define IDI_CMN_OPEN                    10230
#define IDI_RNCAN64                     10231
#define IDI_RNCAN48                     10232
#define IDB_DBEDITOR                    10235
#define IDB_SHAPE_TYPE16                10241
#define IDB_SHAPE_TYPE32                10242
#define IDB_SIM_EXECUTABLE_IMAGE        10243
#define IDB_CMN_NEW                     10244
#define IDB_CMN_STATEICONS              10245
#define IDB_CMN_EDIT32                  10247
#define IDB_CMN_SHOWMAP32               10248
#define IDB_CMN_COPY32                  10249
#define IDB_CMN_NEW32                   10250
#define IDB_CMN_DELETE32                10251
#define IDB_CMN_UP32                    10252
#define IDB_CMN_DOWN32                  10253
#define IDB_CMN_SET_DEFAULT             10254
#define IDB_CMN_EXCEL32                 10255
#define IDB_CMN_LINK32                  10256
#define IDB_CMN_OPTION32                10257
#define IDB_CMN_INFO32                  10258
#define IDB_SIM_ANALYSIS_PAGES          10262
#define IDB_CONTINUOUS_PERIOD1          10263
#define IDB_YEAR_BY_YEAR2               10264
#define IDB_YEAR_BY_YEAR1               10265
#define IDB_CONTINUOUS_PERIOD2          10266
#define IDB_CONTINUOUS_PERIOD1_CHECKED  10267
#define IDB_CONTINUOUS_PERIOD2_CHECKED  10268
#define IDB_YEAR_BY_YEAR1_CHECKED       10269
#define IDB_YEAR_BY_YEAR2_CHECKED       10270
#define IDB_OVER_ALL_YEARS_A            10271
#define IDB_FOR_EACH_YEARS_A            10272
#define IDB_OVER_ALL_YEARS_M            10273
#define IDB_FOR_EACH_YEARS_M            10274
#define IDB_OVER_ALL_YEARS_D            10275
#define IDB_FOR_EACH_YEARS_D            10276
#define IDB_EDIT_WEATHER_GENERATOR      10277
#define IDB_EDIT_PARAMETERS_VARIATIONS  10278
#define IDB_MACTH_STATIONS              10279
#define IDB_EDIT_LOCATIONS              10280
#define IDB_HELP                        10281
#define IDB_DESCRIPTION                 10282
#define IDB_EDIT_PARAMETERS             10283
#define IDB_SHAPE_TYPE17                10284
#define IDD_CMN_NEW_YEAR                15001
#define IDD_CMN_NEW_NAME                15002
#define IDD_CMN_PROGRESS_STEP           15003
#define IDD_CMN_PALETTE_EDITOR          15004
#define IDD_CMN_NEW_PROJECT             15005
#define IDD_CMN_ASK_DIRECTORY           15006
#define IDD_CMN_SELECTION               15007
#define IDD_CMN_ABOUTBOX                15008
#define IDD_CMN_OPTION_DIR              15009
#define IDD_CMN_OPTION_LINK             15010
#define IDD_CMN_OPTION_TIME_FORMAT      15011
#define IDD_CMN_OPTION_ADVANCED         15012
#define IDD_CMN_OPTION_ERROR_LEVEL      15013
#define IDD_MAP_GRID_INTERPOL           15044
#define IDD_SIM_WEATHER_UPDATE          15081
#define IDD_LAYER_PROPERTIES_GENERAL    15121
#define IDD_GRIB_PAGE                   15189
#define IDD_WEATHER_UPDATE_PAGE         15190
#define IDD_SCRIPT_PAGE                 15191
#define IDD_MAP_PREPOST                 15194
#define IDD_CMN_OPTION_CHARTS           15195
#define IDD_CALENDRIER                  15200
#define IDD_MODEL_PAGE                  15203
#define IDD_MODELS_CREDIT               15205
#define IDD_MODELS_FORM                 15207
#define IDD_MODELS_GENERAL              15208
#define IDD_MODELS_OUTPUT               15210
#define IDD_MODELS_TG_INPUT             15211
#define IDD_NORMAL_DIALOG               15212
#define IDD_NORMAL_PAGE                 15213
#define IDD_TG_INPUT                    15216
#define IDD_LINKED_WEA                  15217
#define IDD_DAILY_DIALOG                15220
#define IDD_DAILY_PAGE                  15221
#define IDD_HOURLY_PAGE                 15223
#define IDD_MODELINPUT_EDITOR           15224
#define IDD_TGINPUT_EDITOR              15225
#define IDD_MODELS_INPUT                15226
#define IDD_MAPINPUT_PAGE               15227
#define IDD_HOURLY_DIALOG               15228
#define IDD_VARIABLES_FILTER            15229
#define IDD_VARIABLES                   15230
#define IDD_STATION_DIALOG              15231
#define OLD_IDD_DAILY_DIALOG            15232
#define IDD_CHARTS_PROPETIES            15233
#define IDD_PARAMETERS_VARIATIONS       15234
#define IDD_MODELS_WG_INPUT             15236
#define IDD_WG_INPUT                    15237
#define IDD_MODELS_SSI                  15238
#define IDD_WG_INPUT_MANAGER            15239
#define IDD_PARAMETERS_VARIATIONS_MANAGER 15240
#define IDD_MAP_PAGE                    15241
#define IDD_LAYER_PROPERTIES            15301
#define IDD_MAPCORNER_SELECTOR          15303
#define IDD_GENERAL_PAGE                15305
#define IDD_EXTENT_PAGE                 15306
#define IDD_MASK_PAGE                   15307
#define IDD_CHANGE_RASTER_FORMAT        15308
#define IDD_MERGE_RASTER                15309
#define IDD_EDITING_FIELD               15310
#define IDD_RESAMPLE_SHAPE              15311
#define IDD_EXTRACT_ELEV                15312
#define IDD_SIM_SIMULATION              15332
#define IDD_SIM_VARIATION               15333
#define IDD_SIM_LOC                     15334
#define IDD_SIM_LOC_GENERATE            15335
#define IDD_SIM_ANALYSIS_GENERAL        15337
#define IDD_SIM_ANALYSIS_WHERE          15338
#define IDD_SIM_ANALYSIS_WHEN           15339
#define IDD_SIM_ANALYSIS_WHAT           15340
#define IDD_SIM_ANALYSIS_HOW            15341
#define IDD_SIM_SIMULATED_ANNEALING     15342
#define IDD_SIM_SIMULATED_ANNEALING_PARAMETERS 15343
#define IDD_SIM_IMPORT_SIMULATION       15344
#define IDD_SIM_MAPPING                 15345
#define IDD_SIM_FUNCTION_ANALYSIS       15347
#define IDD_SIM_FUNCTION_TEST           15348
#define IDD_SIM_MERGE_EXECUTABLE        15349
#define IDD_SIM_INPUT_ANALYSIS          15350
#define IDD_SIM_GRAPH_SERIE             15351
#define IDD_SIM_GRAPH                   15352
#define IDD_SIM_ANALYSIS_WHICH          15353
#define IDD_SIM_COPY_EXPORT             15432
#define IDD_SIM_DISPERSAL               15435
#define IDD_SIM_WEATHER_GENERATION      15436
#define IDD_SIM_MODEL_EXECUTION         15438
#define IDD_SIM_LOC_MANAGER             15439
#define IDD_SIM_SCRIPT                  15440
#define IDD_PROJECTION_TRANSFORMATION   15466
#define ID_EDIT32771                    32771
#define ID_SELECTIONNERTOUT             32772
#define IDS_BAD_NORMAL_VER              40200
#define IDS_DBEDIT_CONFIRMDELETE        40201
#define IDS_DBEDIT_CONFIRMDELETESTR     40202
#define IDS_DBEDIT_FORECASTNAME         40203
#define IDS_DBEDIT_MODELSNAME           40204
#define IDS_DBEDIT_NORMALSNAME          40205
#define IDS_DBEDIT_REALTIMENAME         40206
#define IDS_DBEDIT_STATIONEXIST         40207
#define IDS_DBEDIT_UNABLEADDMODIFY      40208
#define IDS_DBEDIT_WEITHERSTR           40209
#define IDS_DBEDITOR_CAPTION            40210
#define IDS_EXITMODEL                   40211
#define IDS_FORECAST_DATAHEAD           40212
#define IDS_FORECAST_REP_NOTFOUND       40213
#define IDS_MODEL_NOTVALID              40214
#define IDS_MODELINPUTINALID            40215
#define IDS_MODELINPUTNAME              40216
#define IDS_MODELS_CAPTION              40217
#define IDS_MODELS_HIDEFORM             40218
#define IDS_MODELS_IDERROR              40219
#define IDS_MODELS_IDEXIST              40220
#define IDS_MODELS_INVARLISTERROR       40221
#define IDS_MODELS_INVARNUMERROR        40222
#define IDS_MODELS_MODELEXIST           40223
#define IDS_MODELS_NAMEMISSING          40224
#define IDS_MODELS_SHOWFORM             40225
#define IDS_MODELS_STRCAPTION           40226
#define IDS_MODELS_VARIDEXIST           40227
#define IDS_MODELS_VARTYPE              40228
#define IDS_NAMEEXIST                   40229
#define IDS_NOFILTERSTR                 40230
#define IDS_NORMAL_DATAHEAD             40231
#define IDS_NORMAL_DATAHEADDESC         40232
#define IDS_NORMAL_DATANOTVALID         40233
#define IDS_NORMAL_NAMEMISSING          40234
#define IDS_NORMAL_REP_NOTFOUND         40235
#define IDS_REALTIME_DATAHEAD           40236
#define IDS_REALTIME_REP_NOTFOUND       40237
#define IDS_RT_CANNOTIMPORT             40238
#define IDS_RT_COPYTOIMPORT             40239
#define IDS_RT_DELETEYEAR               40240
#define IDS_RT_ERRFILEEXIST             40241
#define IDS_RT_ERRORTOCOPY              40242
#define IDS_RT_FILENAMEUSED             40243
#define IDS_SAVE_MODELINPUT             40244
#define IDS_SAVE_RT_YEAR                40245
#define IDS_DB_YEAREXIST                40251
#define IDS_YEARSEXIST                  40252
#define IDS_YEARSTR                     40253
#define IDS_ASK_DELETE_WEATEHR_DB       40255
#define IDS_DB_CREATE_DAILY_BD          40256
#define IDS_DB_SET_AS_DEFAULT_CONFIRM   40257
#define IDS_DB_NEW_WEA_FILE             40258
#define IDS_DB_WEA_EXIST                40259
#define IDS_DB_INVALID_YEAR             40260
#define IDS_DB_ASK_WEA_NAME_TITLE       40261
#define IDS_MODELS_LANGUAGE_HEAD        40262
#define IDS_DB_CONVERT_DATABASE         40263
#define IDS_DB_MATCH_TOOLTIP            40264
#define IDS_DB_LINK_TOOLTIP             40265
#define IDS_LOCATION_MISSING_ID         40266
#define IDS_INPUT_VAR_TITLE             40322
#define IDS_OUTPUT_VAR_TITLE            40323
#define IDS_OUTPUT_VAR_TYPE             40329
#define IDS_OUTPUT_ENTENDED_TYPE        40330
#define IDS_OUTPUT_VAR_DESCRIPTION      40331
#define IDS_DBEDIT_GRAPH_WEATHER        40332
#define IDS_DBEDIT_GRAPH_WEATHER_PROPERTIES 40333
#define IDS_DBEDIT_GRAPH_WEATHER_DESCRIPTION 40336
#define IDS_SIM_PARAMETERS_VARIATIONS_PROPERTIES 40337
#define IDS_SIM_PARAMETERS_VARIATIONS_DESCRIPTION 40338
#define IDS_CMN_NORMAL_PAGE             42350
#define IDS_CMN_DAILY_PAGE              42351
#define IDS_CMN_HOURLY_PAGE             42352
#define IDS_CMN_GRIB_PAGE               42353
#define IDS_CMN_MAPINPUT_PAGE           42354
#define IDS_CMN_MODEL_PAGE              42355
#define IDS_CMN_WEATHERUPDATE_PAGE      42356
#define IDS_CMN_SCRIPT_PAGE             42357
#define ID_SHOW_LATBORDER               42720
#define ID_SHOW_LONBORDER               42721
#define ID_SHOW_LEGENDE                 42722
#define ID_SHOW_TITLE                   42723
#define ID_SHOW_ROSEDESVENTS            42724
#define ID_SHOW_LATGRID                 42725
#define ID_SHOW_LONGRID                 42726
#define ID_SHOW_ADJUST_LATLON           42727
#define ID_MODE_ZOOM                    42728
#define ID_MODE_PAN                     42729
#define ID_MODE_INFO                    42730
#define ID_MODE_EDIT                    42731
#define ID_NODE_ADD                     42732
#define ID_NODE_INSERT                  42733
#define ID_MOVE_NODE                    42734
#define ID_MOVE_SHAPE                   42735
#define ID_DELETE_NODE                  42736
#define ID_DELETE_SHAPE                 42737
#define ID_CUTTING_SHAPE                42738
#define ID_GROUPING_SHAPE               42739
#define ID_ADD_FIRST                    42772
#define ID_ADD_GROUP                    42772
#define ID_ADD_WEATHER_UPDATE           42773
#define ID_ADD_WEATHER_GENERATION       42774
#define ID_ADD_MODEL_EXECUTION          42775
#define ID_ADD_ANALYSIS                 42776
#define ID_ADD_FUNCTION_ANALYSIS        42777
#define ID_ADD_MERGE                    42778
#define ID_ADD_MAP                      42779
#define ID_ADD_IMPORT_SIMULATION        42780
#define ID_ADD_INPUT_ANALYSIS           42781
#define ID_ADD_DISPERSAL                42782
#define ID_ADD_SCRIPT_R                 42783
#define ID_ADD_COPY_EXPORT              42784
#define ID_ADD_MODEL_PARAMETERIZATION   42785
#define ID_ADD_LAST                     42785
#define ID_EDIT_DUPLICATE               42786
#define ID_ITEM_EXPAND_ALL              42790
#define ID_ITEM_COLLAPSE_ALL            42791
#define ID_EDIT                         42792
#define ID_REMOVE                       42794
#define ID_LOC_NEW_LINE                 42795
#define ID_LOC_REMOVE_LINE              42796
#define ID_LOC_GENERATE                 42797
#define ID_LOC_EXTRACT_SSI              42798
#define ID_LOC_DECIMAL_DEGREES          42800
#define ID_LOC_DMS                      42801

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        203
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1222
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
