//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WeatherUpdater.rc
//
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_TOOLBAR           130
#define IDR_TASK_TOOLBAR1               131
#define IDR_TASK_TOOLBAR2               132
#define IDR_TASK                        133
#define IDS_OPTION_CAPTION              155
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_OUTPUT_WND                  162
#define IDI_PROPERTIES_WND              163
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDB_OPTION_ICON                 333
#define IDI_OPTION                      334
#define IDR_MENU_IMAGES                 335
#define IDR_THEME_MENU                  336
#define IDR_POPUP_EDIT                  337
#define IDC_DOCUMENT_PROPERTIES         1013
#define IDS_UPDATE_DIR                  5000
#define IDS_UPDATE_FROM                 5001
#define IDS_NB_STATIONS                 5002
#define IDS_UPDATE_FILE                 5003
#define IDS_UPDATE_END                  5004
#define IDS_CREATE_DATABASE             5005
#define IDS_FROM_DIR                    5006
#define IDS_WORD_TASK                   5007
#define IDS_TASK_NOT_EXIST              5008
#define IDS_CLEAN_LIST                  5009
#define IDS_LOAD_FILE_LIST              5010
#define IDS_SAVE_PROJET                 5011
#define IDS_NB_FILES_CLEARED            5012
#define IDS_NB_FILES_DOWNLOADED         5013
#define IDS_LOAD_PAGE                   5014
#define IDS_NB_FILES_FOUND              5015
#define IDS_ZIP_FILE                    5016
#define IDS_UNZIP_FILE                  5017
#define IDS_INVALID_PASSWORD            5018
#define IDS_INVALID_NOAA_DATFILE        5019
#define IDS_INVALID_NOAA_STNFILE        5020
#define IDS_UNKNOWN_TASK                5021
#define IDS_INVALID_INPUT_TASK          5022
#define IDS_LOAD_STATION_LIST           5023
#define IDS_SERVER_DOWN                 5024
#define IDS_NO_WEATHER                  5025
#define IDS_NO_STATION_INFORMATION      5026
#define IDS_NUMBER_FILES                5027
#define IDS_UNABLE_DOWNLOAD_LIST        5028
#define IDS_UNABLE_DOWNLOAD_DEFENITION  5029
#define IDS_CLIP_WEATHER                5030
#define IDS_SERVER_BUSY                 5031
#define IDS_NO_CC_ENTRY                 5032
#define IDS_MERGE_TYPE                  5033
#define IDS_DOWNLOAD                    5034
#define IDS_WARNING_CORRUPT_FILE        5035
#define IDS_GSOD_OPTIMISATION           5036
#define IDS_GET_STATION_LIST            5037
#define IDS_PRIORITY_RULES              5038
#define IDS_UPLOAD                      5039
#define IDS_CATEGORY_NAME               5040
#define IDS_STATION_ADDED               5041
#define IDS_BOUNDINGBOX_PROPERTY        5042
#define IDS_PROVINCES                   5043
#define IDS_REGION_NAME                 5044
#define IDS_FTP_DIRECTION               5045
#define IDS_FTP_CONNECTION_TYPE         5046
#define ID_ADD_EC_DAILY                 32700
#define ID_ADD_EC_DAILY_P               32701
#define ID_ADD_EC_HOURLY                32702
#define ID_ADD_EC_HOURLY_P              32703
#define ID_ADD_EC_FORECAST              32704
#define ID_ADD_EC_FORECAST_P            32705
#define ID_ADD_EC_OLD_RADAR             32706
#define ID_ADD_EC_OLD_RADAR_P           32707
#define ID_ADD_EC_NEW_RADAR             32708
#define ID_ADD_EC_NEW_RADAR_P           32709
#define ID_ADD_NOAA_GHCND               32710
#define ID_ADD_NOAA_GHCND_P             32711
#define ID_ADD_NOAA_GSOD                32712
#define ID_ADD_NOAA_GSOD_P              32713
#define ID_ADD_NOAA_ISD_LITE            32714
#define ID_ADD_NOAA_ISD_LITE_P          32715
#define ID_ADD_SNOTEL                   32716
#define ID_ADD_SNOTEL_P                 32717
#define ID_ADD_NOMAD_RUC                32718
#define ID_ADD_NOMAD_RUC_P              32719
#define ID_ADD_SM_DAILY                 32720
#define ID_ADD_SM_DAILY_P               32721
#define ID_ADD_SM_HOURLY                32722
#define ID_ADD_SM_HOURLY_P              32723
#define ID_ADD_SM_CIPRA_HOURLY          32724
#define ID_ADD_SM_CIPRA_HOURLY_P        32725
#define ID_ADD_OTHER_DOWNLOADER         32726
#define ID_ADD_OTHER_DOWNLOADER_P       32727
#define ID_ADD_EC_PRCP_RADAR            32728
#define ID_ADD_EC_PRCP_RADAR_P          32729
#define ID_ADD_EC_GRIB_FORECAST         32730
#define ID_ADD_EC_GRIB_FORECAST_P       32731
#define ID_ADD_ACIS                     32732
#define ID_ADD_ACIS_P                   32733
#define ID_ADD_BC_PAWS                  32734
#define ID_ADD_BC_PAWS_P                32735
#define ID_ADD_BC_SNOWPILLOW            32736
#define ID_ADD_BC_SNOWPILLOW_P          32737
#define ID_TOOL_CREATE_HOURLY_DATABSE   32750
#define ID_TOOL_CREATE_HOURLY_DATABSE_P 32751
#define ID_TOOL_CREATE_DAILY_DATABSE    32752
#define ID_TOOL_CREATE_DAILY_DATABSE_P  32753
#define ID_TOOL_HOURLY2DAILY_DATABSE    32754
#define ID_TOOL_HOURLY2DAILY_DATABSE_P  32755
#define ID_TOOL_DAILY2NORMALS_DATABSE   32756
#define ID_TOOL_DAILY2NORMALS_DATABSE_P 32757
#define ID_TOOL_MERGE_DATABASE          32758
#define ID_TOOL_MERGE_DATABASE_P        32759
#define ID_TOOL_MOVE_DATABASE_TOGETHER  32760
#define ID_TOOL_MOVE_DATABASE_TOGETHER_P 32761
#define ID_TOOL_CROP_DATABASE           32762
#define ID_TOOL_CROP_DATABASE_P         32763
#define ID_TOOL_COMPRESS_UNCOMPRESS     32764
#define ID_TOOL_COMPRESS_UNCOMPRESS_P   32765
#define ID_TOOL_DOWNLOAD_UPLOAD         32766
#define ID_TOOL_DOWNLOAD_UPLOAD_P       32767
#define ID_TOOL_CONVERT_DATABASE_OLD    32768
#define ID_TOOL_CONVERT_DATABASE_OLD_P  32769
#define ID_TOOL_CONVERT_DATABASE_NEW    32770
#define ID_TOOL_CONVERT_DATABASE_NEW_P  32771
#define ID_TOOL_OTHER_TOOLS             32772
#define ID_TOOL_OTHER_TOOLS_P           32773
#define ID_MMG_RCM22                    32778
#define ID_MMG_RCM22_P                  32779
#define ID_MMG_GCM10                    32780
#define ID_MMG_GCM10_P                  32781
#define ID_MMG_GCM4                     32782
#define ID_MMG_GCM4_P                   32783
#define ID_MMG_HADGEM2_10               32784
#define ID_MMG_HADGEM2_10_P             32785
#define ID_MMG_MIROC_10                 32786
#define ID_MMG_MIROC_10_P               32787
#define ID_MMG_CESM1_CAM5_10            32788
#define ID_MMG_CESM1_CAM5_10_P          32789
#define ID_TASK_EC_DAILY                32858
#define ID_TASK_EC_HOURLY               32859
#define ID_TASK_EC_FORECAST             32860
#define ID_TASK_EC_OLD_RADAR            32861
#define ID_TASK_EC_NEW_RADAR            32862
#define ID_TASK_NOAA_GHCND              32863
#define ID_TASK_NOAA_GSOD               32864
#define ID_TASK_NOAA_ISD_LITE           32865
#define ID_TASK_SNOTEL                  32866
#define ID_TASK_NOMAD_RUC               32867
#define ID_TASK_SM_DAILY                32868
#define ID_TASK_SM_HOURLY               32869
#define ID_TASK_SM_CIPRA_HOURLY         32870
#define ID_TASK_ADD_OTHER_DOWNLOADER    32871
#define ID_TASK_CREATE_HOURLY_DATABSE   32872
#define ID_TASK_CREATE_DAILY_DATABSE    32873
#define ID_TASK_HOURLY2DAILY_DATABSE    32874
#define ID_TASK_CREATE_NORMALS_DATABSE  32875
#define ID_TASK_MERGE_DATABASE          32876
#define ID_TASK_MOVE_DATABASE_TOGETHER  32877
#define ID_TASK_CROP_DATABASE           32878
#define ID_TASK_COMPRESS_UNCOMPRESS     32879
#define ID_TASK_DOWNLOAD_UPLOAD         32880
#define ID_TASK_CONVERT_DATABASE        32881
#define ID_TASK_OTHER_TOOLS             32882
#define ID_OPTIONS                      32922
#define ID_EXECUTE                      32923
#define ID_LANGUAGE_FRENCH              38000
#define ID_LANGUAGE_ENGLISH             38001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        338
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1018
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
