//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MatchStation.rc
//
#define IDD_DIALOGBAR                   100
#define IDS_TOOLBAR_STANDARD            120
#define IDS_TOOLBAR_CUSTOMIZE           121
#define IDS_PROPERTIES_LOCATION_HEADER  122
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define ID_PROPERTIES                   130
#define ID_OPEN                         131
#define ID_OPEN_WITH                    132
#define ID_SORTING_GROUPBYTYPE          133
#define ID_SORTING_SORTALPHABETIC       134
#define ID_SORTING_SORTBYTYPE           135
#define ID_SORTING_SORTBYACCESS         136
#define ID_SORTPROPERTIES               137
#define ID_EXPAND_ALL                   138
#define IDS_LOCATION_LIST_WND           141
#define IDS_NORMALS_WND                 142
#define IDS_OBSERVATION_WND             143
#define IDS_WEIGHT_CHARTS_WND           144
#define IDS_OUTPUT_WND                  145
#define IDS_PROPERTIES_WND              146
#define IDS_FILEPATH_WND                147
#define IDS_GRADIENT_WND                148
#define IDS_CORRECTION_WND              149
#define IDS_SEARCH_TOOLBAR              150
#define IDS_ESTIMATE_WND                151
#define IDS_OBS_ESTIMATE_WND            152
#define IDR_POPUP_EDIT                  170
#define IDR_MAINFRAME_TOOLBAR           172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDR_MENU_IMAGES                 175
#define IDR_WEIGHT_GRAPH_TOOLBAR        176
#define IDR_OUTPUT_POPUP                177
#define IDR_PROPERTIES                  178
#define IDR_LOCATION_TOOLBAR            179
#define IDR_NORMALS_TOOLBAR             180
#define IDR_OBSERVATION_TOOLBAR         181
#define IDR_SEARCH_TOOLBAR              182
#define IDR_THEME_MENU                  183
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDI_OBSERVATION_WND				331
#define IDI_NORMAL_WND					332
#define IDI_WEIGHT_CHART_WND            333
#define IDI_OUTPUT_WND                  334
#define IDI_PROPERTIES_WND              335
#define IDI_FILEPATH_WND                336
#define IDI_GRADIENT_WND                337
#define IDI_CORRECTION_WND              338
#define IDI_ESTIMATE_N_WND				339
#define IDI_ESTIMATE_O_WND              340
#define IDC_NORMALS_FILEPATH            1021
#define IDC_OBSERVATION_FILEPATH        1022
#define ID_SENDTO_SHOWMAP               32773
#define ID_SENDTO_EXCEL                 32774
#define ID_NB_STATIONS                  32775
#define ID_STATION_VARIABLES            32776
#define ID_STATION_YEAR                 32777
#define ID_SHOW_EMPTY                   32785
#define ID_TABLE_MODE_VISUALISATION     32786
#define ID_TABLE_MODE_EDITION           32787
#define ID_TABLE_SAVE                   32788
#define ID_TABLE_SENDTO_EXCEL           32789
#define ID_TABLE_PERIOD_ENABLED         32790
#define ID_TABLE_PERIOD_BEGIN           32791
#define ID_TABLE_PERIOD_END             32792
#define ID_TABLE_FILTER                 32793
#define ID_TABLE_STAT                   32794
#define ID_TABLE_TM_TYPE                32795
#define ID_TABLE_PERIOD_DESABLED        32796
#define ID_AFFICHAGE_OPTIONS            32800
#define ID_VALIDATION                   32801
#define ID_OPTIONS                      32802
#define ID_EXPORT                       32804
#define ID_AIDE_TEST                    32807
#define ID_GRAPH_COPY                   32829
#define ID_GRAPH_SAVE                   32830
#define ID_GRAPH_OPTIONS                32831
#define ID_GRAPH_ZOOM                   32832
#define ID_GRAPH_PERIOD_ENABLED         32833
#define ID_GRAPH_PERIOD_BEGIN           32834
#define ID_GRAPH_PERIOD_END             32835
#define ID_GRAPH_FILTER                 32836
#define ID_GRAPH_STAT                   32837
#define ID_GRAPH_TM_TYPE                32838
#define ID_GRAPH_PERIOD_DESABLED        32839
#define ID_FLAG_FRENCH                  32850
#define ID_FLAG_ENGLISH                 32851
#define ID_NB_NORMALS_STATION           32860
#define ID_NORMALS_FILEPATH             32861
#define ID_NB_OBSERVATION_STATION       32862
#define ID_OBSERVATION_FILEPATH         32863
#define ID_INDICATOR_NB_LOCATIONS       32880
#define ID_LANGUAGE_FRENCH              38000
#define ID_LANGUAGE_ENGLISH             38001

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        339
#define _APS_NEXT_COMMAND_VALUE         32801
#define _APS_NEXT_CONTROL_VALUE         1021
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
