//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BioSIM.rc
//
#define IDP_OLE_INIT_FAILED             100
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_STATUS              125
#define IDS_PROJECT_WND                 126
#define IDS_SPREADSHEET_WND             127
#define IDS_CHARTS_WND                  128
#define IDS_PROPERTIES_WND              130
#define IDS_EDIT_MENU                   132
#define IDS_OPTION_CAPTION              133
#define IDS_TO_SHOWMAP                  134
#define IDS_OUTPUT_WND                  135
#define IDR_MAINFRAME                   140
#define IDR_BioSIMTYPE                  142
#define IDR_MENU_IMAGES                 143
#define IDR_EXPORT_TOOLBAR              147
#define IDR_EXPORT_TOOLBAR2             148
#define IDR_GRAPH_TOOLBAR               149
#define IDR_POPUP                       150
#define IDB_OPTION_ICON                 153
#define IDI_PROJECT_WND                 156
#define IDI_OUTPUT_WND                  157
#define IDI_PROPERTIES_WND              158
#define IDI_SPREADSHEET_WND             159
#define IDI_EXPORT_WND                  160
#define IDI_CHARTS_WND                  161
#define IDI_OPTION                      162
#define ID_TO_SCRIPT                    163
#define IDD_SIM_EXPORT                  170
#define IDD_ABOUTBOX2                   171
#define IDD_BIOSIM_OPTION               172
#define IDS_EXPORT_WND                  190
#define IDS_PROGRESS_WND                191
#define ID_TOOLS_MACRO                  200
#define ID_WINDOW_MANAGER               201
#define ID_PROPERTIES                   202
#define ID_SORTING_GROUPBYTYPE          203
#define ID_SORTING_SORTALPHABETIC       204
#define ID_SORTING_SORTBYTYPE           205
#define ID_SORTING_SORTBYACCESS         206
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDR_RESULT_TOOLBAR              336
#define IDI_R                           340
#define IDB_BIOSIM_LOGO                 345
#define IDC_VERSION                     1016
#define IDC_WBSF_VERSION                1017
#define IDC_EXPORT_SCRIPT               1019
#define IDC_MAIL_TO_JR                  1020
#define IDC_MAIL_TO_RSA                 1021
#define IDC_BIOSIM_LOGO                 1022
#define IDC_BIOSIM_LOGO2                1023
#define IDC_EXPORT_FILENAME             1104
#define IDC_EXPORT_AUTO                 1105
#define IDC_EXPORT_VARIABLE             1106
#define IDC_EXPORT_STATISTIC            1108
#define IDC_OPTION_LINKCLIMZONES        1507
#define IDC_OPTION_SAVEATRUN            1508
#define IDC_OPTION_JACK                 1509
#define IDC_OPTION_EXPORT_ALL_LINES     1510
#define ID_HOURLY_EDITOR                32780
#define ID_DAILY_EDITOR                 32781
#define ID_NORMALS_EDITOR               32782
#define ID_WEATHER_UPDATER              32783
#define ID_MATCH_STATION                32784
#define ID_STATISTIC                    32794
#define ID_EXECUTE                      32798
#define ID_TOOLS_LOC_EDITOR             32801
#define ID_TOOLS_CLEANUP                32802
#define ID_TOOLS_VALIDATION             32803
#define ID_TOOLS_OPTIONS                32804
#define ID_ADD_EXPORT                   32806
#define ID_EXPORT_NOW                   32810
#define ID_EXPORT_SPREADSHEET1          32811
#define ID_EXPORT_SPREADSHEET2          32812
#define ID_EXPORT_OPEN_DIRECTORY        32813
#define ID_EXPORT_CHECK                 32814
#define ID_EXPORT_NAME                  32815
#define ID_OPEN_WORKING_DIR             32818
#define ID_EXECUTE_MENU                 32819
#define ID_SHOWMAPS                     32820
#define ID_OPEN_OUTPUT_MAP_DIR          32821
#define ID_ADD_GRAPH                    32827
#define ID_EDIT_GRAPH                   32828
#define ID_REMOVE_GRAPH                 32829
#define ID_SAVE_GRAPH                   32830
#define ID_PRINT_GRAPH                  32831
#define IDS_STRING32831                 32831
#define ID_TOOLS_FILE_MANAGER           32899
#define ID_LANGUAGE_FRENCH              32900
#define ID_LANGUAGE_ENGLISH             32901
#define IDS_ASK_CREATE_PROJECT          32902
#define IDS_INDICATOR_NB_EXECUTE        32903
#define ID_TOOLS_TDATE                  32904
#define IDS_CLEANUP                     32904
#define ID_SHOWLOC                      32906
#define ID_TOOLS_MERGEFILES             32911
#define ID_SIMULATIONMENU_MATCHSTATION  32914
#define ID_Menu                         32915
#define ID_DOWNLOAD_DATA                32916
#define ID_HELP_MANUAL                  32917
#define ID_HELP_TUTORIAL                32918
#define ID_SIMULATIONMENU_AFFICHERSTATIONSAPPARI32923 32923

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        350
#define _APS_NEXT_COMMAND_VALUE         32924
#define _APS_NEXT_CONTROL_VALUE         1023
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
